import 'dart:math';

import 'package:flutter/material.dart';
import 'package:ShopAR/constants.dart';
import 'package:ShopAR/models/SubCategory.dart';

class Product {
  final String thumbnail, image, title, description, shortInfo;
  final int price, id, subCategoryID;
  final Color color;
  Product({
    this.id,
    this.subCategoryID,
    this.thumbnail,
    this.image,
    this.title,
    this.price,
    this.description,
    this.shortInfo,
    this.color,
  });

  SubCategory getSubCategory() {
    SubCategory subCategory;
    subCategory = subCategoryList
        .firstWhere((element) => (element.id == this.subCategoryID));
    return subCategory;
  }
}

// Sample Products
List<Product> productList = [
  //spectacles
  Product(
    id: 1,
    subCategoryID: 1,
    title: "Cats Eye",
    shortInfo: "Meow, with a fierce glare",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/1.png",
    image: "assets/images/glasses/birdseye/1.png",
    color: getTileColor(),
  ),
  Product(
    id: 2,
    subCategoryID: 1,
    shortInfo: "Square specs for a squre face",
    title: "Squares",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/2.png",
    image: "assets/images/glasses/birdseye/2.png",
    color: getTileColor(),
  ),
  Product(
    id: 3,
    subCategoryID: 1,
    shortInfo: "Mashup of old and modern for a cool grandpa",
    title: "Slick Bottom",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/3.png",
    image: "assets/images/glasses/birdseye/3.png",
    color: getTileColor(),
  ),
  Product(
    id: 4,
    subCategoryID: 1,
    shortInfo: "Pure Round design for the studious people",
    title: "The World-O",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/4.png",
    image: "assets/images/glasses/birdseye/4.png",
    color: getTileColor(),
  ),
  Product(
    id: 5,
    subCategoryID: 1,
    shortInfo: "A new present for the older generation",
    title: "Old is Gold",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/5.png",
    image: "assets/images/glasses/birdseye/5.png",
    color: getTileColor(),
  ),
  Product(
    id: 6,
    subCategoryID: 1,
    shortInfo: "Slick and lightwaight design",
    title: "Slick Pick",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/6.png",
    image: "assets/images/glasses/birdseye/6.png",
    color: getTileColor(),
  ),
  Product(
    id: 7,
    subCategoryID: 1,
    shortInfo: "Cutness with some simple dimple",
    title: "Little Round",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/7.png",
    image: "assets/images/glasses/birdseye/7.png",
    color: getTileColor(),
  ),
  Product(
    id: 8,
    subCategoryID: 1,
    shortInfo: "Have fun with small eyes",
    title: "Fish Eye",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/8.png",
    image: "assets/images/glasses/birdseye/8.png",
    color: getTileColor(),
  ),

  // sunglasses
  Product(
    id: 9,
    subCategoryID: 2,
    title: "Aviator",
    shortInfo: "Fly with aome cool shades",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/9.png",
    image: "assets/images/glasses/birdseye/9.png",
    color: getTileColor(),
  ),
  Product(
    id: 10,
    subCategoryID: 2,
    title: "Red Devil",
    shortInfo: "Glare of the devils gaze",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/10.png",
    image: "assets/images/glasses/birdseye/10.png",
    color: getTileColor(),
  ),
  Product(
    id: 11,
    subCategoryID: 2,
    title: "Round-Up",
    shortInfo: "Wings are meant for flying",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/11.png",
    image: "assets/images/glasses/birdseye/11.png",
    color: getTileColor(),
  ),
  Product(
    id: 12,
    subCategoryID: 2,
    title: "Serious Man",
    shortInfo: "For all time business",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/glasses/frontview/12.png",
    image: "assets/images/glasses/birdseye/12.png",
    color: getTileColor(),
  ),

  //baseball caps
  Product(
    id: 13,
    subCategoryID: 4,
    title: "New York",
    shortInfo: "It's New York City",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/caps/1.png",
    image: "assets/images/caps/1.png",
    color: getTileColor(),
  ),
  Product(
    id: 14,
    subCategoryID: 4,
    title: "Red Nose",
    shortInfo: "I am a Cute Clown",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/caps/2.png",
    image: "assets/images/caps/2.png",
    color: getTileColor(),
  ),
  Product(
    id: 15,
    subCategoryID: 4,
    title: "Addidas",
    shortInfo: "Be a Sportsman",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/caps/3.png",
    image: "assets/images/caps/3.png",
    color: getTileColor(),
  ),

  // knit caps
  Product(
    id: 16,
    subCategoryID: 5,
    title: "Lit Knit",
    shortInfo: "Comfort for your Soul",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/caps/4.png",
    image: "assets/images/caps/4.png",
    color: getTileColor(),
  ),

  // windsor ties
  Product(
    id: 17,
    subCategoryID: 7,
    title: "Blue Superman",
    shortInfo: "Be the Man Even In Work",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/neckties/1.png",
    image: "assets/images/neckties/1.png",
    color: getTileColor(),
  ),
  Product(
    id: 18,
    subCategoryID: 7,
    title: "Black panther",
    shortInfo: "Its great to be black",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/neckties/2.png",
    image: "assets/images/neckties/2.png",
    color: getTileColor(),
  ),
  Product(
    id: 19,
    subCategoryID: 7,
    title: "Party",
    shortInfo: "Be the soul of the Party",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/neckties/3.png",
    image: "assets/images/neckties/3.png",
    color: getTileColor(),
  ),
  Product(
    id: 20,
    subCategoryID: 7,
    title: "Festival",
    shortInfo: "Its Festival time",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/neckties/4.png",
    image: "assets/images/neckties/4.png",
    color: getTileColor(),
  ),

  // necklaces
  Product(
    id: 21,
    subCategoryID: 10,
    title: "Diamonds",
    shortInfo: "Full of Diamonds in the sky",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/necklaces/1.png",
    image: "assets/images/necklaces/1.png",
    color: getTileColor(),
  ),
  Product(
    id: 22,
    subCategoryID: 10,
    title: "Princess",
    shortInfo: "Made for Nobelity",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/necklaces/2.png",
    image: "assets/images/necklaces/2.png",
    color: getTileColor(),
  ),
  Product(
    id: 23,
    subCategoryID: 11,
    title: "Love Birds",
    shortInfo: "Bonds made to last forever",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/necklaces/3.png",
    image: "assets/images/necklaces/3.png",
    color: getTileColor(),
  ),
  Product(
    id: 24,
    subCategoryID: 12,
    title: "Half Sun",
    shortInfo: "Made for the Goddess",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/necklaces/4.png",
    image: "assets/images/necklaces/4.png",
    color: getTileColor(),
  ),

  // earings
  Product(
    id: 25,
    subCategoryID: 13,
    title: "Pearls",
    shortInfo: "Tears of the Sea",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/earings/1.png",
    image: "assets/images/earings/1.png",
    color: getTileColor(),
  ),
  Product(
    id: 26,
    subCategoryID: 13,
    title: "Glass Drop",
    shortInfo: "Tears of the Melted Sand",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/earings/2.png",
    image: "assets/images/earings/2.png",
    color: getTileColor(),
  ),
  Product(
    id: 27,
    subCategoryID: 14,
    title: "FireWorks",
    shortInfo: "Let it be a Firework",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/earings/3.png",
    image: "assets/images/earings/3.png",
    color: getTileColor(),
  ),
  Product(
    id: 28,
    subCategoryID: 15,
    title: "Black and White",
    shortInfo: "Best of both worlds",
    price: Random().nextInt(500),
    description: dummyText,
    thumbnail: "assets/images/earings/4.png",
    image: "assets/images/earings/4.png",
    color: getTileColor(),
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
